function stgui(ch)
global H_RECORD samp_data
if nargin == 0 % if no input argument, draw the GUI
    ch = 0;
end
% STGUI M-file for stgui.fig
 samp_data=wavread('testsample1.wav');
    
switch ch
       
       case 0   %Draw figure m 
           
           clear global data
            width = 950;
            height = 700;
          %{  
      for i=1:3
          
          
 H_RECORD(i) = uicontrol('Style','pushbutton',... % Speaker button
      'Units','normalized', ...
      'Position',[(100+200*i)/width (height-75)/height 100/width 40/height],...
      'ForegroundColor',[.2 .4 .2],...
      'FontWeight','bold',...
      'String','Speaker',...
      'Enable','on',...
      'CallBack','stgui(i)');
      end
       %}
    
     H_RECORD(5) = uicontrol('Style','text',...
      'Units','normalized', ...
      'Position',[190/width (height-45)/height 400/width 20/height],...
      'FontWeight','bold',...
      'BackgroundColor',[.8 .8 .8],...
      'String','Now..Listen To Individual Speakers');
           
     H_RECORD(1) = uicontrol('Style','pushbutton',... % Speaker button
      'Units','normalized', ...
      'Position',[100/width (height-150)/height 100/width 40/height],...
      'ForegroundColor',[.2 .4 .2],...
      'FontWeight','bold',...
      'String','Speaker1',...
      'Enable','on',...
      'CallBack','stgui(1)');  

     H_RECORD(2) = uicontrol('Style','pushbutton',... % Speaker button
      'Units','normalized', ...
      'Position',[300/width (height-150)/height 100/width 40/height],...
      'ForegroundColor',[.2 .4 .2],...
      'FontWeight','bold',...
      'String','Speaker2',...
      'Enable','on',...
      'CallBack','stgui(2)');
  
     H_RECORD(3) = uicontrol('Style','pushbutton',... % Speaker button
      'Units','normalized', ...
      'Position',[500/width (height-150)/height 100/width 40/height],...
      'ForegroundColor',[.2 .4 .2],...
      'FontWeight','bold',...
      'String','Speaker3',...
      'Enable','on',...
      'CallBack','stgui(3)');
  %{
     H_RECORD(4) = uicontrol('Style','pushbutton',... % Speaker button
      'Units','normalized', ...
      'Position',[700/width (height-150)/height 100/width 40/height],...
      'ForegroundColor',[.2 .4 .2],...
      'FontWeight','bold',...
      'String','Speaker4',...
      'Enable','on',...
      'CallBack','stgui(4)');
    %}       
      %Play speaker1 data
       case 1
           speaker1();
           
      %Play speaker2 data  
       case 2
           speaker2();
           
      %Play speaker3 data  
       case 3
           speaker3();
    
      %Play speaker4 data
       %case 4
        %   speaker4();
      
end           
end